name = input("Enter your name: ")
age = int(input("Enter your age: "))
year = 2025 + (18 - age)
print(f"Hello {name}! You will turn 18 in the year {year}.")
country = input("Enter your country: ")
print(f"You are from {country}. Nice to meet you, {name}!")
